---
- hosts: all
  roles:
    - name: ganto.gentoo_portage
      # https://galaxy.ansible.com/ganto/gentoo_portage include minimal portage for tasks
      # ensurse eix etc gets emerged etc ie docker bare stage3 etc.

- # other roles
     #  ansible-galaxy install vundb.gentoo_bootstrap
    #  https://github.com/vundb/ansible-role-system-bootstrap
    # ansible-galaxy install diodonfrost.ssh_hardening


- name: create overlay directory
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: portage
    mode: 0755
  become: yes
  loop:
    - /etc/portage/repos.conf
    - /var/db/repos/pentoo

- name: install git
  package:
    name:
      - dev-vcs/git
  become: yes

- name: add required pentoo overlay
  template:
    src: pentoo-overlay.j2
    dest: /etc/portage/repos.conf/pentoo.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  register: pentoo_overlay

- include: gentoo-git.xml

- name: sync all portage overlays
  command: eix-sync
  become: yes
  when: pentoo_overlay.changed

 - include: cronjobs.yml

- name: Create pentoo-updater link
    become: yes
  file:
    src: "{{/var/db/repos/pentoo/scripts/pentoo-updater.sh}}"
    dest: "/usr/bin/pentoo-updater"
    state: link

