---

- name: create overlay directory
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  become: yes
  loop:
    - /etc/portage/repos.conf
    - /var/db/repos/pentoo

- name: install git
  package:
    name:
      - dev-vcs/git
  become: yes

- name: add required pentoo overlay
  template:
    src: pentoo-overlay.j2
    dest: /etc/portage/repos.conf/pentoo.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  register: pentoo_overlay

- name: sync all portage overlays
  command: eix-sync
  become: yes
  when: pentoo_overlay.changed
